# Generated by Django 5.0 on 2023-12-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_rename_employee_employeemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeModel',
            new_name='Employee',
        ),
    ]
